// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    FontIcon: typeof import('./src/components/FontIcon.vue')['default']
    Notable: typeof import('./src/components/Notable.vue')['default']
    NotableWind: typeof import('./src/components/NotableWind.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
